Repository wecode-bootcamp-korea/29-1st-Wesop-backend, pull requests merged in 2022-02, with the labels that each got.

#6 [29기 모휘정] Products Views 추가
  bases/migrations/__init__.py
  orders/migrations/0001_initial.py
  orders/models.py
  products/migrations/0001_initial.py
  products/models.py
  products/urls.py
  products/views.py
  users/migrations/0001_initial.py
  users/models.py
  wesop/urls.py
Labels: Status: 동료 리뷰 요청

#7 [혜린] users/view.py 리펙토링
  users/migrations/0002_alter_user_skintype.py
  users/models.py
  users/urls.py
  users/views.py
  wesop/urls.py
Labels: Status: 리뷰 요청, Status: 동료 리뷰 요청

#8 [휘정] Product View 리팩토링
  orders/migrations/0001_initial.py
  products/migrations/0001_initial.py
  products/models.py
  products/urls.py
  products/views.py
  users/migrations/0001_initial.py
  wesop/urls.py
Labels: Status: 리뷰 요청

#10 [혜린] Carts.View 리팩토링
  carts/__init__.py
  carts/admin.py
  carts/apps.py
  carts/migrations/0001_initial.py
  carts/migrations/__init__.py
  carts/models.py
  carts/tests.py
  carts/urls.py
  carts/utils.py
  carts/views.py
  orders/migrations/0001_initial.py
  orders/models.py
  orders/views.py
  products/migrations/0001_initial.py
  users/migrations/0001_initial.py
  users/migrations/0002_alter_user_skintype.py
  users/urls.py
  wesop/settings.py
  wesop/urls.py
Labels: Status: 리뷰 요청

#11 [혜린] Cart, User 프론트와 통신을 위한 일부 오타 수정 임시 코드 작성
  carts/views.py
  users/views.py
Labels: Status: 리뷰 요청
